### ISSUE TITLE
Rodar api no Apache

### ISSUE THREAD

**Issue by chmenegatti** [balta-io/1972#4]
André, blz?

Muito boa essas vídeos aulas. São top demais..
Me seurgiu uma dúvida: como fazer essa api rodar no Apache, sem criar o servidor pelo NodeJS?
Existe essa possibilidade?
Valeu

**Comment by andrebaltieri** [comment]
Bom dia @chmenegatti não sei, mas via Docker tenho um artigo que pode te ajudar: https://balta.io/blog/node-npm-instalacao-configuracao-e-primeiros-passos
