### ISSUE TITLE
refresh-token

### ISSUE THREAD

**Issue by edsonvidal** [balta-io/1972#5]
Ola Balta boa noite,

No refresh-token do "src/controllers/customer-controller.js" na linha 102 acho que deveria retornar o token(tokenData) atualizado veja: https://prnt.sc/s31h97

Da forma que está ele usa o método para atualizar mas retorna o mesmo token

Poderia confirmar se meu entendimento está correto?

**Comment by andrebaltieri** [comment]
@edsonvidal você tem razão! Se puder, faz os testes e envia um PR aqui por favor <3
